postgres:
  tables:
    tags:
      type: application/json;type=tag-type
      columns:
        name: TEXT
        description: TEXT
  functions: {}
  scopes: {}
agent: |
  import Agent from 'npm:@knowlearning/agents/deno.js'
  import * as uuid from "https://deno.land/std@0.207.0/uuid/mod.ts";

  const activeUsers = await Agent.state('active-users')

  Agent.on('child', child => {
    const { environment: { user } } = child

    if (!uuid.validate(user)) return

    activeUsers[user] = Date.now()

    child.on('mutate', async mutation => {
      const { scope, patch } = mutation
      activeUsers[user] = Date.now()
    })

    child.on('close', info => {
      delete activeUsers[user]
    })
  })
