authorize:
  sameDomain:
    postgres: same_domain_authorization
  crossDomain:
    postgres: cross_domain_authorization
postgres:
  tables:
    tag_types:
      type: application/json;type=tag-type
      columns:
        name: TEXT
        description: TEXT
        archived: BOOLEAN
    taggings:
      type: application/json;type=tagging
      columns:
        tag: TEXT
        target: TEXT
        partition: TEXT
        contributor: TEXT
        value: JSON
  functions:
    same_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
    cross_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingDomain
        type: TEXT
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
  queries:
    search-tags:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT *
        FROM tag_types
        WHERE to_tsvector('english', name) @@ plainto_tsquery('english', $1)
           OR to_tsvector('english', description) @@ plainto_tsquery('english', $1)
    taggings-intersection:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT
          target
        FROM taggings
        WHERE partition = $1
          AND tag = ANY($2)
          AND value IS NOT NULL
        GROUP BY target, partition
        HAVING COUNT(DISTINCT tag) = ARRAY_LENGTH($2, 1)
    taggings-for-tag:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT
          id AS tagging,
          target,
          contributor,
          value
        FROM taggings
        WHERE partition = $1
          AND tag = $2
          AND value IS NOT NULL
    taggings-targeting-tags:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT
          taggings.id AS tagging,
          target,
          contributor,
          value
        FROM taggings
        JOIN metadata ON metadata.id = taggings.target
        WHERE partition = $1
          AND tag = $2
          AND value IS NOT NULL
          AND metadata.active_type = 'application/json;type=tag-type'
    top-level-tags: |
      WITH RECURSIVE roots AS (
          -- Identify root tags that are not targeted by any other tags
          SELECT id
          FROM tag_types
          WHERE NOT EXISTS (
              SELECT 1
              FROM taggings
              WHERE tag_types.id = target
                AND taggings.partition = $1
                AND taggings.value IS NOT NULL
          ) AND EXISTS (
              SELECT 1
              FROM taggings
              WHERE tag_types.id = tag
                AND taggings.partition = $1
                AND taggings.value IS NOT NULL
          )
      ),
      traversal AS (
          -- Begin traversal from root tags to follow tag-target relationships
          SELECT tag, target, ARRAY[tag] AS path, ARRAY[target] AS reached, false AS is_cycle
          FROM taggings
          WHERE tag IN (SELECT id FROM roots)

          UNION ALL

          -- Continue traversal, tracking paths and reached tags to detect cycles
          SELECT t.tag, t.target, tt.path || t.tag, tt.reached || t.target, t.tag = ANY(tt.path) OR tt.is_cycle
          FROM traversal tt
          JOIN taggings t ON tt.target = t.tag
          WHERE NOT tt.is_cycle -- Stop recursion when a cycle is detected to avoid infinite loops
            AND t.partition = $1
            AND t.value IS NOT NULL
      ),
      isolated_cycles AS (
          -- Determine isolated cycles not reachable from any root
          SELECT tag, MIN(tag) OVER (PARTITION BY array_to_string(path, ',')) AS representative
          FROM traversal
          WHERE is_cycle
          AND tag NOT IN (SELECT DISTINCT UNNEST(reached) FROM traversal)
      )

      -- Select all root tags and unique representatives from isolated cycles
      SELECT id AS tag
      FROM roots

      UNION

      SELECT DISTINCT representative
      FROM isolated_cycles
    tagging-contributor: |
      SELECT contributor
      FROM taggings
      WHERE partition = $1
        AND tag = $2
        AND target = $3
    tagging-for-target:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT value
        FROM taggings
        WHERE partition = $1
          AND tag = $2
          AND target = $3
          AND value IS NOT NULL
    taggings-for-target:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT
          tag,
          value
        FROM taggings
        WHERE partition = $1
          AND target = $2
          AND value IS NOT NULL
agent: |
  import Agent from 'npm:@knowlearning/agents/deno.js'
  import * as uuid from "https://deno.land/std@0.207.0/uuid/mod.ts";

  const TAGGING_TYPE = 'application/json;type=tagging'

  const PILA_INTERNATIONAL_PARTITION = 'PILA'
  const PILA_THAILAND_PARTITION = 'PILA Thailand'

  const ADMIN_TAG = "36e1b060-ed49-11ee-be89-5b04faf266ea"
  const TEACHER_TAG = "49bf66a0-ed49-11ee-be89-5b04faf266ea"
  const TRAINER_TAG = "8ae541e0-ed49-11ee-be89-5b04faf266ea"
  const PILA_CONTENT_TAG = "1a53db50-e248-11ee-ab5f-07f4a7408770"
  const PILA_COMPETENCY_TAG = "f760dad0-f133-11ee-804e-27f76a81958c"

  Agent.on('child', child => {
    const { environment: { user } } = child

    child.on('mutate', async mutation => {
      const { scope, patch } = mutation

      if (scope === 'tags') {
        Agent.log('GOT TAGGING PATCH', patch)
        patch.forEach(async ({ path, value: patchValue={} }) => {
          if (path.length === 2) {
            const [ tag, target ] = path
            const { partition=user, value=null } = patchValue || {}
            let contributor = user

            // The only agents able to overwrite contributor are trusted domains
            if (isTrustedDomain(user)) contributor = patchValue.contributor || user

            const apply = () => applyTagging(partition, tag, target, contributor, value)
            const reject = () => Agent.log(`User tagging rejected`, partition, user, contributor, tag)

            if (partition === contributor) apply()
            else if (isPILAPartition(partition)) {
              if (isSuperAdmin(partition, contributor)) apply()
              else if (tag === PILA_CONTENT_TAG) {
                if (await isAdmin(partition, contributor)) apply()
                else reject()
              }
              else if (tag === TRAINER_TAG || tag === TEACHER_TAG) {
                if (await isTrainer(partition, contributor)) apply()
                else reject()
              }
              else if (await hasTag(partition, PILA_COMPETENCY_TAG, tag)) {
                if (await isAdmin(partition, contributor)) apply()
                else reject()
              }
              else reject()
            }
            else reject()
          }
        })
      }
    })
  })

  function isTrustedDomain(domain) {
    return [
      'app.pilaproject.org',
      'thailand.pilaproject.org',
      'matching-customizer-reference.netlify.app',
      'f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898',
      'c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:9898',
      '0c9c64fc-559e-40d4-916b-852f6d108a17.localhost:9898',
      'c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061',
      '0c9c64fc-559e-40d4-916b-852f6d108a17.localhost:6061'
    ].includes(domain)
  }

  function isPILAPartition(partition) {
    return [
      PILA_INTERNATIONAL_PARTITION,
      PILA_THAILAND_PARTITION
    ].includes(partition)
  }

  function isSuperAdmin(partition, user) {
    if (partition === PILA_INTERNATIONAL_PARTITION) {
      return [
        "f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f",
        "c0f3a481-d4d5-4133-a198-94a325aa4536",
        "0c9c64fc-559e-40d4-916b-852f6d108a17"
      ].includes(user)
    }
    else if (partition === PILA_THAILAND_PARTITION) {
      return [
        "f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f",
        "c0f3a481-d4d5-4133-a198-94a325aa4536",
        "0c9c64fc-559e-40d4-916b-852f6d108a17"
      ].includes(user)
    }
    else return false
  }

  async function isAdmin(partition, user) {
    return (
      isSuperAdmin(partition, user) ||
      await hasTag(partition, ADMIN_TAG, user)
    )
  }

  async function isTrainer(partition, user) {
    return (
      await isAdmin(partition, user) ||
      await hasTag(partition, TRAINER_TAG, user)
    )
  }

  async function hasTag(partition, tag, user) {
    const tagging = await Agent.query('tagging-for-target', [partition, tag, user])
    Agent.log('CHECKED OUT TAG', partition, tag, user, tagging)
    return !!tagging[0]
  }

  async function applyTagging(partition, tag, target, contributor, value) {
    const id = `tagging/${JSON.stringify([partition, tag, target])}`
    const tagging = await Agent.state(id)
    const md = await Agent.metadata(id)

    if (md.active_type !== TAGGING_TYPE) md.active_type = TAGGING_TYPE

    //  TODO: consider making 'authority' the agent that specified contributor
    const taggingData = {
      tag,
      target,
      contributor,
      partition,
      value
    }

    Object.assign(tagging, taggingData)
  }