authorize:
  sameDomain:
    postgres: same_domain_authorization
  crossDomain:
    postgres: cross_domain_authorization
postgres:
  tables:
    tag_types:
      type: application/json;type=tag-type
      columns:
        name: TEXT
        description: TEXT
        archived: BOOLEAN
    taggings:
      type: application/json;type=tagging
      columns:
        tag: TEXT
        content: TEXT
        partition: TEXT
        contributor: TEXT
        active: BOOLEAN
  functions:
    same_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
    cross_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingDomain
        type: TEXT
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
  scopes:
    tags: SELECT * FROM tag_types
    my-tags: |
      SELECT
        metadata.id as id,
        tag_types.name as name,
        description
      FROM tag_types
      LEFT JOIN metadata
        ON metadata.id = tag_types.id
      WHERE metadata.owner = $REQUESTER
        AND archived IS NOT true
    my-archived-tags: |
      SELECT
        metadata.id as id,
        tag_types.name as name,
        description
      FROM tag_types
      LEFT JOIN metadata
        ON metadata.id = tag_types.id
      WHERE metadata.owner = $REQUESTER
        AND archived IS TRUE
    search: |
      SELECT *
      FROM tag_types
      WHERE to_tsvector('english', name) @@ plainto_tsquery('english', $1)
         OR to_tsvector('english', description) @@ plainto_tsquery('english', $1)
    taggings-intersection: |
      SELECT
        content,
        partition
      FROM taggings
      WHERE tag = ANY($1)
        AND active IS TRUE
      GROUP BY content, partition
      HAVING COUNT(DISTINCT tag) = ARRAY_LENGTH($1, 1)
    taggings-for-tag: |
      SELECT
        content,
        partition,
        contributor
      FROM taggings
      WHERE tag = $1
        AND active IS TRUE
    tagging-contributor: |
      SELECT contributor
      FROM taggings
      WHERE partition = $1
        AND tag = $2
        AND content = $3
    tags-for-content: |
      SELECT DISTINCT tag
      FROM taggings
      WHERE content = $1
        AND active IS TRUE
  crossDomainQueries:
    search-tags:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT *
        FROM tag_types
        WHERE to_tsvector('english', name) @@ plainto_tsquery('english', $1)
           OR to_tsvector('english', description) @@ plainto_tsquery('english', $1)
    taggings:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT content
        FROM taggings
        WHERE tag = ANY($1)
          AND active IS TRUE
        GROUP BY content
        HAVING COUNT(DISTINCT tag) = ARRAY_LENGTH($1, 1)
    tags-for-content:
      domains:
      - f74e9cb3-2b53-4c85-9b0c-f1d61b032b3f.localhost:9898
      - c0f3a481-d4d5-4133-a198-94a325aa4536.localhost:6061
      - matching-customizer-reference.netlify.app
      - thailand.pilaproject.org
      - app.pilaproject.org
      body: |
        SELECT DISTINCT tag
        FROM taggings
        WHERE content = $1
          AND active IS TRUE
agent: |
  import Agent from 'npm:@knowlearning/agents/deno.js'
  import * as uuid from "https://deno.land/std@0.207.0/uuid/mod.ts";

  const TAGGING_TYPE = 'application/json;type=tagging'

  Agent.on('child', child => {
    const { environment: { user } } = child

    child.on('mutate', async mutation => {
      const { scope, patch } = mutation

      if (scope === 'tags') {
        Agent.log('GOT TAGGING PATCH', patch)
        patch.forEach(async ({ path, value: patchValue }) => {
          if (path.length === 2) {
            const [ tag, content ] = path
            const {
              partition=user,
              contributor=user,
              value
            } = patchValue

            const id = `tagging/${JSON.stringify([partition, tag, content])}`
            const tagging = await Agent.state(id)
            const md = await Agent.metadata(id)

            if (md.active_type !== TAGGING_TYPE) md.active_type = TAGGING_TYPE

            const taggingData = {
              tag,
              content,
              contributor,
              partition: user, // TODO: collect partition from patch value
              active: !!value
            }

            Object.assign(tagging, taggingData)
          }
        })
      }
    })
  })
